#!/bin/sh
# Acme startup script

export SHELL=$PLAN9/bin/rc
export acmeshell=$PLAN9/bin/rc

pgrep plumber || plumber &

if [ -f "$HOME/acme.dump" ]; then
    DUMP="-l $HOME/acme.dump"
else
    DUMP=""
fi

acme -a -f /mnt/font/'Liberation Mono'/11a/font $DUMP
