#!/bin/bash
# Lint C source with gcc

# Persistent settings (change as appropriate)
INCLUDE=$PLAN9/include
CFLAGS="-Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wconversion"

if [ $# -eq 0 ]; then
    if [ -z $samfile ]; then
        echo "Usage: clint [FILE]"
        exit 1
    else
        file=$samfile
    fi
else
    file=$1
fi

gcc -fsyntax-only -I$INCLUDE $CFLAGS $file
